// <auto-generated />
using System;
using GursagarBookStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GursagarBooks.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231117215748_AddCoverTypeToDb")]
    partial class AddCoverTypeToDb : AddCoverTypeToDbBase
    {
    }

    internal class AddCoverTypeToDbBase
    {
    }
}